%YAML 1.2
%TAG ! tag:fawkesrobotics.org,cfg/
---
# Configuration meta information document
include:
  # reads files ending in .yaml from conf.d config subdir
  # - !ignore-missing conf.d/
  # Reads the host-specific configuration file, no failure if missing
  - !host-specific host.yaml
---
# Main configuration document

llsfrb:
  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log

  sps:
    enable: false
    host: !ipv4 192.168.1.77
    port: !tcp-port 502
    test-lights: true

  mps:
    enable: true
    # type: 1(incoming station), 2(singel p&p), 3(double p&p), 4(delivery station)
    stations:
      C-BS:
        active: true
        host: !ipv4 127.0.0.1
        port: !tcp-port 4501
        type: BS
      C-CS1:
        active: true
        host: !ipv4 127.0.0.1
        port: !tcp-port 4502
        type: CS
      C-CS2:
        active: true
        host: !ipv4 127.0.0.1
        port: !tcp-port 4503
        type: CS
      C-RS1:
        active: true
        host: !ipv4 127.0.0.1
        port: !tcp-port 4504
        type: RS
      C-RS2:
        active: true
        host: !ipv4 127.0.0.1
        port: !tcp-port 4505
        type: RS
      C-DS:
        active: true
        host: !ipv4 127.0.0.1
        port: !tcp-port 4506
        type: DS
      M-BS:
        active: false
        host: !ipv4 192.168.2.33
        port: !tcp-port 502
        type: BS
      M-CS1:
        active: false
        host: !ipv4 192.168.2.30
        port: !tcp-port 502
        type: CS
      M-CS2:
        active: false
        host: !ipv4 192.168.2.32
        port: !tcp-port 502
        type: CS  
      M-RS1:
        active: false
        host: !ipv4 192.168.2.31
        port: !tcp-port 502
        type: RS
      M-RS2:
        active: false
        host: !ipv4 192.168.2.34
        port: !tcp-port 502
        type: RS
      M-DS:
        active: false
        host: !ipv4 192.168.2.29
        port: !tcp-port 502
        type: DS

  clips:
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: [time, signal, gamestate]
    unwatch-rules: [retract-time,
                    game-update-gametime-points, game-update-last-time,
                    net-send-beacon, net-send-GameState, net-send-OrderInfo,
                    net-send-MachineInfo, net-send-RobotInfo,
                    exploration-send-MachineReportInfo, net-broadcast-MachineInfo,
                    net-send-VersionInfo]

  comm:
    protobuf-dirs: ["@BASEDIR@/src/msgs"]

    server-port: !tcp-port 4444
    
    public-peer:
      host: !ipv4 172.26.255.255
      #host: !ipv4 127.0.0.1
      port: !udp-port 4444
      #send-port: !udp-port 4444
      #recv-port: !udp-port 4445

    cyan-peer:
      host: !ipv4 172.26.255.255
      #host: !ipv4 127.0.0.1
      port: !udp-port 4441
      #send-port: !udp-port 4441
      #recv-port: !udp-port 4446

    magenta-peer:
      host: !ipv4 172.26.255.255
      #host: !ipv4 127.0.0.1
      port: !udp-port 4442
      #send-port: !udp-port 4442
      #recv-port: !udp-port 4447

  mongodb:
    enable: false
    hostport: localhost
    collections:
      text-log: llsfrb.log
      clips-log: llsfrb.clipslog
      protobuf: llsfrb.protobuf

  game:
    teams: [Carologistics]
    crypto-keys:
      Carologistics: randomkey
    # whenever a random field should be generated or not (e.g. used from mongodb)
    random-field: false

  shell:
    refbox-host: localhost
    refbox-port: 4444

  simulation:
    enable: false
    # synchronize refbox time with the time of a simulation 
    time-sync:
      enable: false
      # estimate time by using the last given simulation time speed
      # (helps reducing the amount of messages to send)
      estimate-time: false
